services:  
  hs-admin:
    image: runyf/hs-admin:latest
    # image: hs-admin
    container_name: hs-admin  
    network_mode: host
    restart: unless-stopped  
    volumes:  
      - ./app:/app
      - ./config:/etc/headscale
      - ./data:/var/lib/headscale
    environment:
      - TZ=Asia/Shanghai
      - FLASK_DEBUG=False
