name: Build and Push Docker Image

on:
  # push:
    # branches: [ main ]
    # tags: [ 'v*' ]
  workflow_dispatch:
    inputs:
      version:
        description: "自定义版本号，例如 v1.0.0"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: zht98/hs-admin
          tags: |
            # 删掉 type=ref,event=branch（避免生成main标签）
            # type=ref,event=tag  # 标签触发时生成：runyf/hs-admin:v1.0.0
            # 仅main分支触发时生成latest标签（无main标签）
            # type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ github.event.inputs.version }}
            type=raw,value=latest

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
